"""
report_utils.py
----------------
Yeh file downloadable PDF report banati hai - patient ka naam,
prediction, confidence score, X-ray, aur Grad-CAM heatmap ke saath.

Use kaise karein:
    from report_utils import generate_report

    generate_report(
        patient_name="Ram Kumar",
        prediction="Pneumonia",
        confidence=92.5,
        original_image_path="uploads/xray1.png",
        gradcam_image_path="gradcam_outputs/xray1_gradcam.png",
        save_path="reports/report1.pdf"
    )
"""

import os
from datetime import datetime
from fpdf import FPDF


def generate_report(patient_name, prediction, confidence,
                     original_image_path, gradcam_image_path, save_path):
    """
    PDF report banata hai aur save_path pe save karta hai.
    Return: save_path
    """
    pdf = FPDF()
    pdf.add_page()

    # ---- Title ----
    pdf.set_font("Arial", "B", 16)
    pdf.cell(0, 10, "PneumoVision AI - Medical Summary Report", ln=True, align="C")
    pdf.ln(5)

    # ---- Patient info ----
    pdf.set_font("Arial", "", 12)
    pdf.cell(0, 8, f"Patient Name: {patient_name if patient_name else 'N/A'}", ln=True)
    pdf.cell(0, 8, f"Date: {datetime.now().strftime('%d-%m-%Y %H:%M')}", ln=True)
    pdf.ln(5)

    # ---- Prediction result ----
    pdf.set_font("Arial", "B", 13)
    pdf.cell(0, 8, f"Prediction: {prediction}", ln=True)
    pdf.cell(0, 8, f"Confidence Score: {confidence}%", ln=True)
    pdf.ln(5)

    # ---- Disclaimer ----
    pdf.set_font("Arial", "I", 10)
    pdf.multi_cell(
        0, 6,
        "Note: This report is generated by an AI-assisted system and is intended "
        "to support healthcare professionals. It is NOT a substitute for "
        "professional medical diagnosis."
    )
    pdf.ln(8)

    # ---- Original X-ray image ----
    if original_image_path and os.path.exists(original_image_path):
        pdf.set_font("Arial", "B", 11)
        pdf.cell(0, 8, "Original X-ray:", ln=True)
        pdf.image(original_image_path, w=80)
        pdf.ln(5)

    # ---- Grad-CAM heatmap image ----
    if gradcam_image_path and os.path.exists(gradcam_image_path):
        pdf.set_font("Arial", "B", 11)
        pdf.cell(0, 8, "Grad-CAM Heatmap (Affected Regions):", ln=True)
        pdf.image(gradcam_image_path, w=80)

    pdf.output(save_path)
    return save_path
