"""
report_utils.py
----------------
This file generates a downloadable PDF report - patient details,
prediction, confidence score, X-ray, and Grad-CAM heatmap.

Usage:
    from report_utils import generate_report

    generate_report(
        patient_name="Ram Kumar",
        patient_age="20",
        patient_gender="Male",
        patient_id="1002",
        doctor_name="Dr. Sharma",
        hospital_name="City Hospital",
        prediction="Pneumonia",
        confidence=92.5,
        original_image_path="uploads/xray1.png",
        gradcam_image_path="gradcam_outputs/xray1_gradcam.png",
        save_path="reports/report1.pdf"
    )
"""

import os
from datetime import datetime
from fpdf import FPDF


def generate_report(patient_name, prediction, confidence,
                     original_image_path, gradcam_image_path, save_path,
                     patient_age=None, patient_gender=None, patient_id=None,
                     doctor_name=None, hospital_name=None):
    """
    Generates a PDF report and saves it at save_path.
    Return: save_path
    """
    pdf = FPDF()
    pdf.add_page()

    # ---- Title ----
    pdf.set_font("Arial", "B", 16)
    pdf.cell(0, 10, "PneumoVision AI - Medical Summary Report", ln=True, align="C")
    pdf.ln(5)

    # ---- Patient info ----
    pdf.set_font("Arial", "", 12)
    pdf.cell(0, 8, f"Patient Name: {patient_name if patient_name else 'N/A'}", ln=True)
    pdf.cell(0, 8, f"Age: {patient_age if patient_age else 'N/A'}", ln=True)
    pdf.cell(0, 8, f"Gender: {patient_gender if patient_gender else 'N/A'}", ln=True)
    pdf.cell(0, 8, f"Patient ID: {patient_id if patient_id else 'N/A'}", ln=True)
    pdf.cell(0, 8, f"Doctor: {doctor_name if doctor_name else 'N/A'}", ln=True)
    pdf.cell(0, 8, f"Hospital: {hospital_name if hospital_name else 'N/A'}", ln=True)
    pdf.cell(0, 8, f"Date: {datetime.now().strftime('%d-%m-%Y %H:%M')}", ln=True)
    pdf.ln(5)

    # ---- Prediction result ----
    pdf.set_font("Arial", "B", 13)
    pdf.cell(0, 8, f"Prediction: {prediction}", ln=True)
    pdf.cell(0, 8, f"Confidence Score: {confidence}%", ln=True)
    pdf.ln(5)

    # ---- Disclaimer ----
    pdf.set_font("Arial", "I", 10)
    pdf.multi_cell(
        0, 6,
        "Note: This report is generated by an AI-assisted system and is intended "
        "to support healthcare professionals. It is NOT a substitute for "
        "professional medical diagnosis."
    )
    pdf.ln(8)

    # ---- Original X-ray image ----
    if original_image_path and os.path.exists(original_image_path):
        pdf.set_font("Arial", "B", 11)
        pdf.cell(0, 8, "Original X-ray:", ln=True)
        pdf.image(original_image_path, w=80)
        pdf.ln(5)

    # ---- Grad-CAM heatmap image ----
    if gradcam_image_path and os.path.exists(gradcam_image_path):
        pdf.set_font("Arial", "B", 11)
        pdf.cell(0, 8, "Grad-CAM Heatmap (Affected Regions):", ln=True)
        pdf.image(gradcam_image_path, w=80)

    pdf.output(save_path)
    return save_path